<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "edrush_dependency_tree"
 *
 * Auto generated by Extension Builder 2016-03-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Extension dependency tree',
	'description' => 'An extension for the TYPO3 CMS to visualize dependencies between installed extensions.',
	'category' => 'module',
	'author' => 'Wolfram Eberius',
	'author_email' => 'edrush@posteo.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-',
			'extbase' => '6.2.0-',
			'fluid' => '6.2.0-'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);